[workspace]
members = [
    "nucypher-core",
    # "nucypher-core-python",
    "nucypher-core-wasm",
]

# Prevents feature conflicts between [dependencies] and [dev-dependencies]
# Will be the default in 2021 edition.
resolver = "2"
