[package]
name = "nucypher-core-python"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
version = "0.4.0-alpha.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.16"
nucypher-core = { path = "../nucypher-core" }
umbral-pre = { version = "0.7.0-alpha.0", features = ["bindings-python", "serde-support"] }
derive_more = { version = "0.99", default-features = false, features = ["from", "as_ref"] }

[build-dependencies]
pyo3-build-config = "*"
