[package]
name = "nucypher-core-python"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
version = "0.0.1"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.15"
nucypher-core = { path = "../nucypher-core" }
umbral-pre = { path = "../../rust-umbral/umbral-pre", features = ["bindings-python", "serde-support"] }
# umbral-pre = { version = "0.5", features = ["bindings-python", "serde-support"] }

[build-dependencies]
pyo3-build-config = "*"
