[package]
name = "nucypher-core-python"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
version = "0.8.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18"
nucypher-core = { path = "../nucypher-core" }
# TODO: Replace with a new release after this PR is merged and released: https://github.com/nucypher/rust-umbral/pull/122
umbral-pre = { git = "https://github.com/piotr-roslaniec/rust-umbral.git", rev = "5a279039d1e44e415f2cfac85282fc5102d41a6c", features = ["bindings-python"] }
ferveo = { package = "ferveo-pre-release", git = "https://github.com/nucypher/ferveo.git", rev = "9795e2969f525fc7ee3a7721dca368287f4825c8", features = ["bindings-python"] }
derive_more = { version = "0.99", default-features = false, features = ["from", "as_ref"] }

[build-dependencies]
pyo3-build-config = "*"
