[package]
name = "nucypher-core-wasm"
version = "0.1.0"
authors = [
    "Piotr Roslaniec <p.roslaniec@gmail.com>",
    "Bogdan Opanchuk <bogdan@opanchuk.net>"
]
edition = "2018"
license = "GPL-3.0-only"
description = "NuCypher network core data structures"
repository = "https://github.com/nucypher/nucypher-core/tree/master/nucypher-core-wasm"
readme = "README.md"
categories = ["cryptography", "no-std"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nucypher-core = { path = "../nucypher-core" }
umbral-pre-bindings-wasm = { path = "../../rust-umbral/umbral-pre-bindings-wasm" }
wasm-bindgen = "0.2.74"
js-sys = "0.3.51"
wee_alloc = "0.4"
