name: nucypher-core

on:
  pull_request:
    paths:
      - "nucypher-core/**"
      - "Cargo.*"
  push:
    branches:
      - master
    tags:
      - v*

defaults:
  run:
    working-directory: nucypher-core

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            rust: 1.56.1 # MSRV
          - target: x86_64-unknown-linux-gnu
            rust: stable

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - run: ${{ matrix.deps }}
      - run: cargo check --all-features
      - run: cargo test --release --all-features

  wasm-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.56.1 # MSRV
          - stable
        target:
          - wasm32-unknown-unknown

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo install wasm-pack
      - run: wasm-pack test --node

  trigger-wheels:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Wheels
          token: ${{ secrets.PERSONAL_TOKEN }}

  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/tarpaulin@v0.1
        with:
          version: latest
          # Only checking the coverage of the main library,
          # bindings are covered by their language's tests.
          # Also have to exclude `nucypher-core-python` explicitly,
          # since it cannot be compiled for testing
          # (https://github.com/PyO3/pyo3/issues/340)
          args: --exclude-files nucypher-core-wasm/** --exclude-files nucypher-core-python/** --workspace --exclude nucypher-core-python --all-features -- --test-threads 1
      - uses: codecov/codecov-action@v1
      - uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
